# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-09 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
