# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-09 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161109_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo')),
            ],
        ),
    ]
